In [61]:
import pandas as pd
from numpy import diag
import numpy as np
from sklearn.decomposition import TruncatedSVD
dataset= pd.read_csv("/content/movie_review.csv")
print(dataset)
old_dataset=dataset.values
old_dataset

   shimla  manali  kashmir  goa  kerela
0       1       1        1    0       0
1       3       3        3    0       0
2       4       4        4    0       0
3       5       5        5    0       0
4       0       2        0    4       4
5       0       0        0    5       5
6       0       1        0    2       2


array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 2, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 1, 0, 2, 2]])

In [62]:
svd = TruncatedSVD(n_components =3)
result= svd.fit_transform(old_dataset)
print(result)

[[ 1.71737671 -0.22451218  0.01454344]
 [ 5.15213013 -0.67353654  0.04363033]
 [ 6.86950685 -0.89804872  0.05817378]
 [ 8.58688356 -1.12256089  0.07271722]
 [ 1.9067881   5.62055093 -0.87952624]
 [ 0.90133537  6.9537622   0.912571  ]
 [ 0.95339405  2.81027546 -0.43976312]]


In SVD the data set D  is decomposed into three matrices namely U,$\Sigma$ and V, i.e.,

$\begin{equation}
D= U \Sigma V^{T}
\end{equation}$

- The result of fit and transform functions under TruncatedSVD  is $\textbf{U $\Sigma$}$. The dot product of $\textbf{U $\Sigma$}$ gives us the new data point to be projected along vectors given by V.

- In order to find  $\Sigma$, $\textbf{singular_values_}$ under TruncatedSVD is used. 

- Matrix $\textbf{V_T}$ is obtained by using $\textbf{components_}$ function

- To obtain U, we can divide transformed data by values obtained by singular_values_


In [63]:
sigma = svd.singular_values_
v = svd.components_ # 
u = result/svd.singular_values_
# where result is transform value and is sigma is sigular value of svd 

print(sigma.shape)
print(v.shape)
print(u.shape)
print(sigma)
print(v)
print(u)

(3,)
(3, 5)
(7, 3)
[12.48101469  9.50861406  1.34555971]
[[ 0.56225841  0.5928599   0.56225841  0.09013354  0.09013354]
 [-0.12664138  0.02877058 -0.12664138  0.69537622  0.69537622]
 [ 0.40966748 -0.80479152  0.40966748  0.0912571   0.0912571 ]]
[[ 0.13759913 -0.02361145  0.01080847]
 [ 0.41279738 -0.07083435  0.03242542]
 [ 0.5503965  -0.09444581  0.04323389]
 [ 0.68799563 -0.11805726  0.05404236]
 [ 0.15277509  0.59110096 -0.65365084]
 [ 0.07221651  0.73131186  0.67820922]
 [ 0.07638754  0.29555048 -0.32682542]]


In [64]:
s= diag(svd.singular_values_)
data_new = np.dot(result, v)# here we  are doing dotproduct between result and v
data_new = np.round(data_new,2) # here we use round function for maximum 2 place of decimal
print(data_new)
print(old_dataset)

[[ 1.  1.  1.  0.  0.]
 [ 3.  3.  3.  0.  0.]
 [ 4.  4.  4.  0.  0.]
 [ 5.  5.  5.  0.  0.]
 [ 0.  2.  0.  4.  4.]
 [ 0. -0.  0.  5.  5.]
 [ 0.  1.  0.  2.  2.]]
[[1 1 1 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [5 5 5 0 0]
 [0 2 0 4 4]
 [0 0 0 5 5]
 [0 1 0 2 2]]


***Finding the best rank for the given data set using Frobenius Norm. The Frobenius Norm has to be small***

***∣(A−B)F∣=∑ij(Aij−Bij)2−−−−−−−−−−−−−√ ***

Where A and B represents old and new data set respectively

In [65]:
data_diff = np.subtract(old_dataset, data_new)
data_squarediff = np.square(data_diff)
print('Frobenius Norm = ', np.sqrt(data_squarediff.sum()))


Frobenius Norm =  0.0


In [66]:
import pandas as pd
from numpy import diag
import numpy as np
from sklearn.decomposition import TruncatedSVD
data= pd.read_csv("/content/iris.data")
print(data)
old_dataset=idata.values
old_dataset

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3

In [67]:
idata=data.drop(data.iloc[:, [ 4]], axis=1,inplace=False)

In [68]:
print(idata)

     5.1  3.5  1.4  0.2
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  2.3
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]


In [73]:
svd = TruncatedSVD(n_components =3)
result= svd.fit_transform(old_dataset)
print(result)

[[ 5.56903610e+00  1.98238953e+00 -2.37430341e-01]
 [ 5.44325676e+00  2.10489891e+00 -8.01239677e-03]
 [ 5.43313694e+00  1.88003274e+00 -1.46288888e-02]
 [ 5.87147945e+00  2.33837351e+00  1.17642857e-01]
 [ 6.47340943e+00  2.33547564e+00  2.44856636e-01]
 [ 5.51223900e+00  2.08003469e+00  2.36436825e-01]
 [ 5.84711328e+00  2.15846798e+00 -1.18904339e-02]
 [ 5.15577720e+00  1.78435151e+00 -5.52212942e-02]
 [ 5.64151444e+00  2.00057817e+00 -2.18485705e-01]
 [ 6.26108962e+00  2.43690323e+00 -9.15197903e-03]
 [ 5.74839178e+00  2.03026161e+00  9.34661040e-02]
 [ 5.47712256e+00  1.98814267e+00 -2.41517850e-01]
 [ 4.94748669e+00  2.05708298e+00 -8.22186872e-03]
 [ 6.52079389e+00  2.92776915e+00 -2.28291770e-02]
 [ 6.78525516e+00  2.83592857e+00  4.21598824e-01]
 [ 6.26771334e+00  2.61871654e+00  2.22969099e-01]
 [ 5.92549790e+00  2.27807271e+00  5.42277783e-02]
 [ 6.64389183e+00  2.40147343e+00 -2.65027676e-02]
 [ 6.09060722e+00  2.37090544e+00  2.62207425e-01]
 [ 6.25025237e+00  2.13163982e+

In [74]:
sigma = svd.singular_values_
v = svd.components_ # 
u = result/svd.singular_values_
print(sigma.shape)
print(v.shape)
print(u.shape)
print(sigma)
print(v)
print(u)


(3,)
(3, 4)
(149, 3)
[95.76845708 17.5720318   3.46929666]
[[ 0.75072761  0.37895098  0.51424022  0.16840786]
 [ 0.28698073  0.54547651 -0.70810225 -0.34451218]
 [-0.49942327  0.67502587  0.05471884  0.54029836]]
[[ 5.81510476e-02  1.12815043e-01 -6.84376011e-02]
 [ 5.68376783e-02  1.19786883e-01 -2.30951618e-03]
 [ 5.67320087e-02  1.06990060e-01 -4.21667278e-03]
 [ 6.13091161e-02  1.33073599e-01  3.39097137e-02]
 [ 6.75943795e-02  1.32908685e-01  7.05781777e-02]
 [ 5.75579806e-02  1.18371895e-01  6.81512273e-02]
 [ 6.10546881e-02  1.22835424e-01 -3.42733271e-03]
 [ 5.38358595e-02  1.01544974e-01 -1.59171439e-02]
 [ 5.89078556e-02  1.13850134e-01 -6.29769451e-02]
 [ 6.53773675e-02  1.38680789e-01 -2.63799263e-03]
 [ 6.00238529e-02  1.15539377e-01  2.69409374e-02]
 [ 5.71913000e-02  1.13142447e-01 -6.96157964e-02]
 [ 5.16609209e-02  1.17065744e-01 -2.36989497e-03]
 [ 6.80891609e-02  1.66615288e-01 -6.58034732e-03]
 [ 7.08506262e-02  1.61388768e-01  1.21522852e-01]
 [ 6.54465315e-02  1.4

In [75]:
s= diag(svd.singular_values_)
data_new = np.dot(result, v)# here we  are doing dotproduct between result and v matrix
data_new = np.round(data_new,1) # here we use round function for maximum 2 place of decimal
print(data_new)
print(old_dataset)

[[4.9 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.3]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.9 3.3 1.5 0.3]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.7 4.1 1.3 0.1]
 [5.7 4.4 1.5 0.4]
 [5.3 4.  1.4 0.3]
 [5.1 3.5 1.4 0.2]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.8 0.4]
 [4.9 3.3 1.8 0.4]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.5 0.3]
 [4.8 3.1 1.6 0.2]
 [5.3 3.5 1.6 0.2]
 [5.3 4.  1.4 0.3]
 [5.5 4.2 1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 3.3 1.3 0.1]
 [5.4 3.6 1.4 0.1]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.2]
 [4.4 2.4 1.5 0.1]
 [4.4 3.2 1.3 0.3]
 [4.9 3.6 1.7 0.5]
 [5.2 3.7 1.8 0.5]
 [4.8 3.  1.5 0.2]
 [5.2 3.7 1.5 0.3]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.

In [76]:
data_diff = np.subtract(old_dataset, data_new)
data_squarediff = np.square(data_diff)
print('Frobenius Norm = ', np.sqrt(data_squarediff.sum()))

Frobenius Norm =  1.9798989873223327
